"""DAD Asset Management System — analysis payload for ISO doc generation.

Exports get_analysis(lang) so the Thai docx has native Thai prose while the
English docx keeps the same tables with English descriptions. Technical nouns
(library / product / AWS service names, protocols, schema field names) stay
English in both languages.
"""


# -------------------- English --------------------
_EN = {
    "description": (
        "Thai real-estate asset management platform covering land parcels, buildings, "
        "vehicles, and jewelry, with tenant lease management, rent collection, utility "
        "billing, Thai tax compliance, document OCR, and FlowAccount accounting sync."
    ),

    "frontend_intro": (
        "Every page is rendered by a single Next.js 14 App Router instance. Routes "
        "live under frontend/app/[locale]/..., where [locale] is resolved to /en or "
        "/th by next-intl before any page-level code runs. The (dashboard) route "
        "group hosts authenticated operational screens; /admin/* hosts admin-only "
        "views; /auth/* hosts the public login flow."
    ),

    "auth_description": (
        "Authentication uses email-and-password with bcrypt-hashed credentials. On "
        "success the backend issues a JWT that carries user id, organization id, and "
        "role; the token is stored in an HTTP-only, SameSite=Lax cookie to resist "
        "CSRF. Every API call passes through an Elysia JWT middleware that rejects "
        "expired or tampered tokens and loads the user context. Role-based access "
        "control (admin, manager, accountant, viewer) is enforced per handler, and "
        "all queries are organization-scoped so users of organization A cannot see "
        "records of organization B."
    ),

    "tech_stack": [
        ("Frontend", "Framework", "Next.js 14 (App Router)", "14.x"),
        ("Frontend", "UI Library", "Ant Design 6", "6.x"),
        ("Frontend", "Styling", "Tailwind CSS", "3.x"),
        ("Frontend", "Forms", "react-hook-form + Zod", "latest"),
        ("Frontend", "i18n", "next-intl (EN / TH)", "latest"),
        ("Backend", "Runtime", "Bun", "1.x"),
        ("Backend", "Framework", "Elysia.js", "latest"),
        ("Backend", "ORM", "Drizzle ORM", "latest"),
        ("Backend", "Language", "TypeScript", "5.x"),
        ("Database", "Primary", "MySQL 8.x (AWS RDS)", "8.x"),
        ("Cache", "Session / Jobs", "Redis 7", "7.x"),
        ("Storage", "Files", "AWS S3 / MinIO", "-"),
        ("OCR", "Document Processing", "Python + Tesseract", "-"),
        ("Infrastructure", "Containerization", "Docker Compose", "-"),
        ("Infrastructure", "Reverse Proxy", "Nginx", "-"),
        ("Testing (FE)", "Unit", "Vitest + React Testing Library", "latest"),
        ("Testing (FE)", "E2E", "Playwright", "latest"),
        ("Testing (BE)", "Unit", "Bun test", "latest"),
    ],

    "api_services": [
        ("API-001", "Authentication", "/api/auth",
         "JWT-based login, register, and refresh endpoints"),
        ("API-002", "Users", "/api/users", "User account management and roles"),
        ("API-003", "Audit Logs", "/api/audit-logs", "Activity audit trail"),
        ("API-004", "Properties", "/api/properties", "CRUD for all property types"),
        ("API-005", "Land Parcels", "/api/land-parcels", "Land parcel CRUD"),
        ("API-006", "Buildings", "/api/buildings", "Building CRUD with units"),
        ("API-007", "Vehicles", "/api/vehicles", "Vehicle asset CRUD"),
        ("API-008", "Jewelry", "/api/jewelry", "Jewelry asset CRUD"),
        ("API-009", "Tenants", "/api/tenants", "Tenant master data"),
        ("API-010", "Leases", "/api/leases", "Lease agreements"),
        ("API-011", "Rent Collection", "/api/rent-collection",
         "Monthly rent collection workflow"),
        ("API-012", "Payments", "/api/payments", "Payment ledger"),
        ("API-013", "Billing", "/api/billing", "Property billing"),
        ("API-014", "Utilities", "/api/utilities", "Utility account CRUD"),
        ("API-015", "Utility Packages", "/api/utility-packages", "Billing package config"),
        ("API-016", "Tax Reports", "/api/tax-reports", "Tax report generation"),
        ("API-017", "Land Tax", "/api/land-tax", "Thai land tax calculation"),
        ("API-018", "Vehicle Tax", "/api/vehicle-tax", "Thai vehicle tax"),
        ("API-019", "Documents", "/api/documents", "Document upload and metadata"),
        ("API-020", "Document Groups", "/api/document-groups", "Folder organization"),
        ("API-021", "OCR", "/api/ocr", "Thai OCR extraction"),
        ("API-022", "Projects", "/api/projects", "Project workspaces"),
        ("API-023", "Search", "/api/search", "Full-text search"),
        ("API-024", "FlowAccount", "/api/flowaccount", "Accounting sync proxy"),
        ("API-025", "Tags", "/api/tags", "Tagging system"),
        ("API-026", "Entity Links", "/api/entity-links", "Cross-entity relationships"),
        ("API-027", "Reports", "/api/reports", "Generated reports"),
        ("API-028", "Dashboard", "/api/dashboard", "Dashboard statistics"),
        ("API-029", "Bulk Operations", "/api/bulk-operations", "Batch processing"),
        ("API-030", "Location", "/api/location", "Thai province and district lookups"),
    ],

    "db_tables": [
        ("organizations", "Company / organization records", "id, name, tax_id"),
        ("users", "User accounts scoped to an organization", "id, email, organization_id"),
        ("roles", "Role definitions", "id, name"),
        ("permissions", "Permission grants", "id, name, action"),
        ("audit_logs", "Activity audit trail", "id, user_id, action, entity"),
        ("asset_types", "Asset type enum (land / building / vehicle / jewelry)", "id, name"),
        ("property_types", "Property sub-categories", "id, name"),
        ("land_deed_types", "Thai land deed classifications", "id, name"),
        ("building_types", "Building classifications", "id, name"),
        ("vehicle_types", "Vehicle categories", "id, name"),
        ("jewelry_types", "Jewelry categories", "id, name"),
        ("tenants", "Tenant records", "id, name, organization_id"),
        ("leases", "Lease agreements", "id, property_id, tenant_id"),
        ("payment_methods", "Payment method types", "id, name"),
        ("tax_types", "Tax categories", "id, name"),
        ("tax_calculations", "Computed tax amounts", "id, property_id, tax_type"),
        ("land_tax_assessments", "Thai land tax assessments", "id, property_id"),
        ("vehicle_tax_records", "Vehicle tax records", "id, vehicle_id"),
        ("utility_accounts", "Utility service accounts", "id, property_id"),
        ("utility_bills", "Utility billing records", "id, account_id"),
        ("documents", "Uploaded documents", "id, entity_type, entity_id"),
        ("document_groups", "Document folders", "id, name"),
        ("ocr_results", "Extracted OCR text", "id, document_id"),
        ("tags", "Tag definitions", "id, name, color"),
        ("entity_links", "Cross-entity links", "id, source_id, target_id"),
        ("projects", "Project workspaces", "id, name, organization_id"),
        ("reports", "Generated reports", "id, type, organization_id"),
        ("provinces", "Thai provinces", "id, name_th, name_en"),
        ("districts", "Thai districts", "id, province_id, name"),
        ("flowaccount_contacts", "FlowAccount contact sync", "id, fa_id, local_id"),
    ],

    "infrastructure": [
        ("Frontend", "Next.js 14", "SSR + static web UI", "Docker"),
        ("Backend API", "Elysia.js on Bun", "REST API server", "Docker"),
        ("Database", "MySQL 8 (AWS RDS)", "Primary data store", "AWS"),
        ("Cache", "Redis 7", "Session and job queue", "Docker"),
        ("Object Storage", "AWS S3 / MinIO", "Document and image storage", "AWS / Docker"),
        ("OCR Service", "Python + Tesseract", "Thai document text extraction", "Docker"),
        ("Reverse Proxy", "Nginx", "SSL termination and routing", "Docker"),
        ("CI / CD", "GitHub Actions", "Build, test, and deploy pipeline", "GitHub"),
        ("Container Registry", "GHCR", "Docker image storage", "GitHub"),
    ],

    "external_services": [
        ("FlowAccount", "FlowAccount API", "Thai accounting and invoicing sync", "REST + OAuth"),
        ("AWS S3", "Amazon Web Services", "Document and image storage", "SDK"),
        ("AWS RDS", "Amazon Web Services", "Managed MySQL database", "SDK"),
        ("AWS SES", "Amazon Web Services", "Transactional email", "SDK"),
        ("AWS EC2", "Amazon Web Services", "Application hosting", "SSH / Docker"),
    ],

    "security": [
        ("Password Storage", "bcrypt", "Passwords hashed with bcrypt before storage"),
        ("Session Tokens", "JWT", "HTTP-only cookies with short expiry"),
        ("Authorization", "RBAC", "Role-based access control at handler level"),
        ("Data Isolation", "Org scoping", "Every query filtered by organization_id"),
        ("Transport", "TLS 1.2+", "Enforced at Nginx"),
        ("CSRF", "SameSite=Lax", "Cookies flagged to block cross-site posting"),
        ("Input Validation", "Zod", "Schema validation on all API handlers"),
        ("SQL Injection", "Drizzle ORM", "Parameterized queries only"),
    ],

    "deployment": [
        ("Frontend", "dad-frontend", "3000"),
        ("Backend API", "dad-backend", "3002"),
        ("Database", "AWS RDS MySQL", "3306"),
        ("Redis", "dad-redis", "6379"),
        ("MinIO (dev)", "dad-minio", "9000"),
        ("OCR Service", "dad-ocr", "8000"),
        ("Nginx", "dad-nginx", "80 / 443"),
    ],

    "roles": [
        ("Admin", "Full CRUD, user management, system config", "All modules"),
        ("Manager", "CRUD on properties, leases, billing", "Assigned properties"),
        ("Accountant", "Read/write on billing, tax, and reports", "Billing and tax modules"),
        ("Viewer", "Read-only", "Assigned modules"),
    ],

    "navigation": [
        ("Dashboard", "/dashboard", "Overview with key metrics and charts"),
        ("Assets", "/assets", "Unified asset inventory"),
        ("Land Parcels", "/land-parcels", "Land parcel management"),
        ("Buildings", "/buildings", "Building management"),
        ("Tenants", "/tenants", "Tenant master data"),
        ("Leases", "/leases", "Lease agreements"),
        ("Rent Collection", "/rent-collection", "Rent payment workflow"),
        ("Tax", "/tax", "Tax compliance"),
        ("Property Billing", "/property-billing", "Property billing"),
        ("Utility Billing", "/utility-billing", "Utility billing"),
        ("Documents", "/documents", "Document management"),
        ("Projects", "/projects", "Project organization"),
        ("Admin — Users", "/admin/users", "User and role administration"),
        ("Admin — Audit Logs", "/admin/audit-logs", "Activity audit trail"),
        ("Admin — OCR Results", "/admin/ocr-results", "OCR extraction review"),
    ],

    "frontend_modules": [
        {"id": "FE-home", "route": "/", "title": "Home",
         "description_en": "Landing page that redirects authenticated users to the dashboard.",
         "description_th": "หน้าแรกที่จะพาผู้ใช้ที่ล็อกอินแล้วไปยังแดชบอร์ดโดยอัตโนมัติ",
         "screenshot": "FE-home.png"},
        {"id": "FE-auth-login", "route": "/auth/login", "title": "Login",
         "description_en": "Email-and-password login form issuing a JWT on success.",
         "description_th": "ฟอร์มล็อกอินด้วยอีเมลและรหัสผ่าน เมื่อสำเร็จจะออก JWT ให้ผู้ใช้",
         "screenshot": "FE-auth-login.png"},
        {"id": "FE-dashboard", "route": "/dashboard", "title": "Dashboard",
         "description_en": "Overview with KPI cards, recent activity, and cross-module charts.",
         "description_th": "หน้าสรุปภาพรวม แสดงการ์ด KPI กิจกรรมล่าสุด และกราฟข้อมูลข้ามโมดูล",
         "screenshot": "FE-dashboard.png"},
        {"id": "FE-assets", "route": "/assets", "title": "Assets",
         "description_en": "Unified inventory of land, buildings, vehicles, and jewelry.",
         "description_th": "คลังรายการทรัพย์สินรวม ทั้งที่ดิน อาคาร ยานพาหนะ และอัญมณี",
         "screenshot": "FE-assets.png"},
        {"id": "FE-assets-building", "route": "/assets/building", "title": "Buildings (asset view)",
         "description_en": "Building assets filtered from the unified inventory.",
         "description_th": "รายการอาคารที่กรองจากคลังทรัพย์สินรวม",
         "screenshot": "FE-assets-building.png"},
        {"id": "FE-assets-jewelry", "route": "/assets/jewelry", "title": "Jewelry (asset view)",
         "description_en": "Jewelry assets filtered from the unified inventory.",
         "description_th": "รายการอัญมณีที่กรองจากคลังทรัพย์สินรวม",
         "screenshot": "FE-assets-jewelry.png"},
        {"id": "FE-assets-land", "route": "/assets/land", "title": "Land (asset view)",
         "description_en": "Land parcels filtered from the unified inventory.",
         "description_th": "รายการแปลงที่ดินที่กรองจากคลังทรัพย์สินรวม",
         "screenshot": "FE-assets-land.png"},
        {"id": "FE-assets-map", "route": "/assets/map", "title": "Asset map",
         "description_en": "Map view plotting all assets by geolocation.",
         "description_th": "มุมมองแผนที่ของทรัพย์สินทั้งหมดตามพิกัดภูมิศาสตร์",
         "screenshot": "FE-assets-map.png"},
        {"id": "FE-assets-new", "route": "/assets/new", "title": "New asset (selector)",
         "description_en": "Selector for the type of asset to create.",
         "description_th": "หน้าเลือกประเภททรัพย์สินที่ต้องการสร้างใหม่",
         "screenshot": "FE-assets-new.png"},
        {"id": "FE-assets-create", "route": "/assets/create", "title": "Create asset",
         "description_en": "Multi-step create form for a new asset record.",
         "description_th": "ฟอร์มสร้างทรัพย์สินใหม่แบบหลายขั้นตอน",
         "screenshot": "FE-assets-create.png"},
        {"id": "FE-assets-vehicle", "route": "/assets/vehicle", "title": "Vehicles (asset view)",
         "description_en": "Vehicle assets filtered from the unified inventory.",
         "description_th": "รายการยานพาหนะที่กรองจากคลังทรัพย์สินรวม",
         "screenshot": "FE-assets-vehicle.png"},
        {"id": "FE-buildings", "route": "/buildings", "title": "Buildings",
         "description_en": "Building catalog with area, status, and unit count.",
         "description_th": "แคตาล็อกอาคาร พร้อมข้อมูลพื้นที่ สถานะ และจำนวนยูนิต",
         "screenshot": "FE-buildings.png"},
        {"id": "FE-buildings-new", "route": "/buildings/new", "title": "New building",
         "description_en": "Building create form including unit configuration.",
         "description_th": "ฟอร์มสร้างอาคารใหม่ พร้อมตั้งค่าข้อมูลยูนิต",
         "screenshot": "FE-buildings-new.png"},
        {"id": "FE-documents", "route": "/documents", "title": "Documents",
         "description_en": "Uploaded documents grouped by folder, with Thai OCR preview.",
         "description_th": "เอกสารที่อัปโหลด จัดกลุ่มตามโฟลเดอร์ พร้อมตัวอย่างผลลัพธ์ OCR ภาษาไทย",
         "screenshot": "FE-documents.png"},
        {"id": "FE-land-parcels", "route": "/land-parcels", "title": "Land parcels",
         "description_en": "Land parcels with Thai deed type, area, and ownership columns.",
         "description_th": "รายการแปลงที่ดิน พร้อมคอลัมน์ประเภทโฉนด พื้นที่ และกรรมสิทธิ์",
         "screenshot": "FE-land-parcels.png"},
        {"id": "FE-land-parcels-new", "route": "/land-parcels/new", "title": "New land parcel",
         "description_en": "Create form for a new land parcel including Thai deed details.",
         "description_th": "ฟอร์มสร้างแปลงที่ดินใหม่ พร้อมรายละเอียดโฉนดไทย",
         "screenshot": "FE-land-parcels-new.png"},
        {"id": "FE-leases", "route": "/leases", "title": "Leases",
         "description_en": "Lease agreements with status, term, and tenant references.",
         "description_th": "สัญญาเช่า พร้อมสถานะ ระยะเวลา และข้อมูลผู้เช่า",
         "screenshot": "FE-leases.png"},
        {"id": "FE-leases-create", "route": "/leases/create", "title": "Create lease",
         "description_en": "Multi-step lease creation wizard.",
         "description_th": "ตัวช่วยสร้างสัญญาเช่าแบบหลายขั้นตอน",
         "screenshot": "FE-leases-create.png"},
        {"id": "FE-projects", "route": "/projects", "title": "Projects",
         "description_en": "Project workspaces grouping related assets and documents.",
         "description_th": "พื้นที่โครงการ สำหรับจัดกลุ่มทรัพย์สินและเอกสารที่เกี่ยวข้อง",
         "screenshot": "FE-projects.png"},
        {"id": "FE-projects-create", "route": "/projects/create", "title": "Create project",
         "description_en": "Project creation form.",
         "description_th": "ฟอร์มสร้างโครงการใหม่",
         "screenshot": "FE-projects-create.png"},
        {"id": "FE-property-billing", "route": "/property-billing", "title": "Property billing",
         "description_en": "Billing workspace for property-level charges.",
         "description_th": "พื้นที่จัดการบิลสำหรับค่าใช้จ่ายระดับอสังหาริมทรัพย์",
         "screenshot": "FE-property-billing.png"},
        {"id": "FE-rent-collection", "route": "/rent-collection", "title": "Rent collection",
         "description_en": "Overview of rent collection activity across tenants.",
         "description_th": "ภาพรวมการเก็บค่าเช่าจากผู้เช่าทุกราย",
         "screenshot": "FE-rent-collection.png"},
        {"id": "FE-rent-collection-monthly", "route": "/rent-collection/monthly", "title": "Monthly rent",
         "description_en": "Monthly rent run with payment status per lease.",
         "description_th": "รอบเก็บค่าเช่ารายเดือน พร้อมสถานะการชำระเงินของแต่ละสัญญาเช่า",
         "screenshot": "FE-rent-collection-monthly.png"},
        {"id": "FE-rent-collection-overdue", "route": "/rent-collection/overdue", "title": "Overdue rent",
         "description_en": "Overdue rent workspace with aging buckets and reminders.",
         "description_th": "พื้นที่จัดการค่าเช่าค้างชำระ พร้อมช่วงอายุหนี้และการแจ้งเตือน",
         "screenshot": "FE-rent-collection-overdue.png"},
        {"id": "FE-tax", "route": "/tax", "title": "Tax",
         "description_en": "Entry point for Thai tax compliance workflows.",
         "description_th": "จุดเริ่มต้นของงานปฏิบัติตามกฎหมายภาษีไทย",
         "screenshot": "FE-tax.png"},
        {"id": "FE-tax-overview", "route": "/tax/overview", "title": "Tax overview",
         "description_en": "Cross-tax-type dashboard summarising pending obligations.",
         "description_th": "แดชบอร์ดภาษีรวมทุกประเภท สรุปภาระภาษีที่ค้างดำเนินการ",
         "screenshot": "FE-tax-overview.png"},
        {"id": "FE-tax-building", "route": "/tax/building", "title": "Building tax",
         "description_en": "Building tax calculations and filing status.",
         "description_th": "การคำนวณภาษีอาคารและสถานะการยื่นแบบ",
         "screenshot": "FE-tax-building.png"},
        {"id": "FE-tax-vehicle", "route": "/tax/vehicle", "title": "Vehicle tax",
         "description_en": "Vehicle tax records with renewal tracking.",
         "description_th": "บันทึกภาษียานพาหนะ พร้อมติดตามการต่อภาษี",
         "screenshot": "FE-tax-vehicle.png"},
        {"id": "FE-tax-signboard", "route": "/tax/signboard", "title": "Signboard tax",
         "description_en": "Thai signboard tax (ภาษีป้าย) workspace.",
         "description_th": "พื้นที่จัดการภาษีป้ายตามกฎหมายไทย",
         "screenshot": "FE-tax-signboard.png"},
        {"id": "FE-tax-reports", "route": "/tax/reports", "title": "Tax reports",
         "description_en": "Tax report generator producing exportable summaries.",
         "description_th": "ตัวสร้างรายงานภาษีที่สามารถส่งออกไปใช้งานต่อได้",
         "screenshot": "FE-tax-reports.png"},
        {"id": "FE-tenants", "route": "/tenants", "title": "Tenants",
         "description_en": "Tenant master list with status, contact, and lease counts.",
         "description_th": "รายชื่อผู้เช่าหลัก พร้อมสถานะ ข้อมูลติดต่อ และจำนวนสัญญาเช่า",
         "screenshot": "FE-tenants.png"},
        {"id": "FE-tenants-create", "route": "/tenants/create", "title": "Create tenant",
         "description_en": "Tenant registration form with Thai ID validation.",
         "description_th": "ฟอร์มลงทะเบียนผู้เช่า พร้อมตรวจสอบเลขบัตรประชาชนไทย",
         "screenshot": "FE-tenants-create.png"},
        {"id": "FE-utility-billing", "route": "/utility-billing", "title": "Utility billing",
         "description_en": "Utility billing workspace driving monthly utility invoices.",
         "description_th": "พื้นที่จัดการบิลสาธารณูปโภคสำหรับการออกใบแจ้งหนี้รายเดือน",
         "screenshot": "FE-utility-billing.png"},
        {"id": "FE-utility-billing-meter-reading", "route": "/utility-billing/meter-reading",
         "title": "Meter reading",
         "description_en": "Meter reading entry with OCR assist for utility meters.",
         "description_th": "บันทึกเลขมิเตอร์พร้อมระบบช่วยอ่านด้วย OCR",
         "screenshot": "FE-utility-billing-meter-reading.png"},
        {"id": "FE-admin-audit-logs", "route": "/admin/audit-logs", "title": "Audit logs",
         "description_en": "Admin-only view of the system-wide activity audit trail.",
         "description_th": "มุมมองเฉพาะผู้ดูแลระบบ แสดงบันทึกกิจกรรมทั้งระบบ",
         "screenshot": "FE-admin-audit-logs.png"},
        {"id": "FE-admin-users", "route": "/admin/users", "title": "Users & roles",
         "description_en": "Admin workspace for user accounts and role assignments.",
         "description_th": "พื้นที่จัดการบัญชีผู้ใช้และการกำหนดบทบาทสำหรับผู้ดูแลระบบ",
         "screenshot": "FE-admin-users.png"},
        {"id": "FE-admin-ocr-results", "route": "/admin/ocr-results", "title": "OCR results",
         "description_en": "OCR job history with extracted-text review.",
         "description_th": "ประวัติงาน OCR และหน้าตรวจทานข้อความที่ถูกดึงออกมา",
         "screenshot": "FE-admin-ocr-results.png"},
    ],

    "module_design": [
        {"name": "Authentication",
         "description": "JWT login over email/password. RBAC enforced at the Elysia middleware layer. "
                        "Session cookies are HTTP-only and SameSite=Lax.",
         "diagram": "dad-access-control.png"},
        {"name": "Property management",
         "description": "Core CRUD across four asset types (land, building, vehicle, jewelry). "
                        "Each type has its own Thai-specific metadata (deed types, vehicle categories, metal types).",
         "diagram": "dad-module-assets.png"},
        {"name": "Tenant and lease",
         "description": "Tenant master data plus lease lifecycle management. Leases link a property "
                        "to a tenant with term, rent amount, and payment schedule.",
         "diagram": "dad-module-leases.png"},
        {"name": "Rent collection",
         "description": "Monthly rent run per lease, with payment recording, overdue tracking, and "
                        "integration into property billing.",
         "diagram": "dad-module-rent-collection.png"},
        {"name": "Tax compliance",
         "description": "Thai-specific tax calculators for land, building, vehicle, and signboard taxes. "
                        "Assessments, filing status, and exportable tax reports.",
         "diagram": "dad-module-tax.png"},
        {"name": "Utility billing",
         "description": "Utility accounts with meter readings, rate packages, and monthly bill generation.",
         "diagram": "dad-module-utility-billing.png"},
        {"name": "Documents and OCR",
         "description": "Document upload to AWS S3, Thai OCR through a Python + Tesseract sidecar, "
                        "and polymorphic linkage to any entity in the system.",
         "diagram": "dad-module-documents.png"},
        {"name": "FlowAccount sync",
         "description": "Outbound sync of contacts, invoices, and receipts to the FlowAccount API, with "
                        "a retry queue backed by Redis.",
         "diagram": "dad-integration-flowaccount.png"},
    ],

    "test_scope": [
        "Frontend (Next.js 14) — Dashboard, Assets, Leases, Tax, Documents",
        "Backend API (Elysia.js / Bun) — all 30 handler groups",
        "Database (MySQL) — schema integrity and foreign-key constraints",
        "External integrations — FlowAccount, AWS S3, OCR service",
        "Security — JWT authentication, RBAC, input validation",
    ],

    "test_tools": [
        ("Vitest", "latest", "Frontend unit testing", "Frontend"),
        ("React Testing Library", "latest", "Component testing", "Frontend"),
        ("Playwright", "latest", "End-to-end browser testing", "Frontend"),
        ("Bun test", "built-in", "Backend unit testing", "Backend"),
        ("Artillery", "2.x", "Load and performance testing", "API"),
    ],

    "test_infrastructure": [
        ("Application server", "AWS EC2 (ap-southeast-1)", "AWS", "ap-southeast-1"),
        ("Database", "AWS RDS MySQL 8.x", "AWS", "ap-southeast-1"),
        ("Cache", "Redis 7", "Docker", "local"),
        ("Storage", "AWS S3 / MinIO", "AWS / Docker", "-"),
        ("E2E runner", "Playwright (Chromium)", "local / CI", "-"),
        ("Load testing", "Artillery", "local", "-"),
    ],

    "test_data": [
        ("Test organizations", "3", "Admin org, manager org, and accountant org"),
        ("Test users", "12", "Four roles times three users each"),
        ("Test properties", "20", "Land (8), buildings (6), vehicles (4), jewelry (2)"),
        ("Test tenants", "10", "With varied statuses"),
        ("Test leases", "8", "Active, expired, and pending"),
        ("Test tax records", "15", "Land tax and vehicle tax calculations"),
        ("Test documents", "10", "PDF, images, and Thai OCR samples"),
    ],

    "test_strategy": [
        ("Unit testing", "Isolated with mocks (Vitest + Bun test)", "100% automated", ">= 80%"),
        ("Integration testing", "API with real database", "95% automated", ">= 85%"),
        ("E2E testing", "Browser workflows (Playwright)", "100% automated", "100% critical paths"),
        ("Performance testing", "Load testing (Artillery)", "100% automated", "< 500 ms p95"),
        ("Security testing", "Manual plus automated", "70% automated", "All auth paths"),
    ],

    "test_categories": [
        ("Frontend unit tests", "Vitest", "42", "40", "2", "0", "95.2%"),
        ("Frontend E2E tests", "Playwright", "25", "24", "1", "0", "96.0%"),
        ("Backend unit tests", "Bun test", "30", "29", "1", "0", "96.7%"),
        ("Backend integration", "Manual + API", "15", "15", "0", "0", "100%"),
        ("Performance tests", "Artillery", "5", "5", "0", "0", "100%"),
        ("Security tests", "Manual", "6", "6", "0", "0", "100%"),
        ("TOTAL", "-", "123", "119", "4", "0", "96.7%"),
    ],

    "test_timeline": [
        ("Unit testing", "Week 1-2", "Complete", "72"),
        ("Integration testing", "Week 2-3", "Complete", "20"),
        ("E2E testing", "Week 3-4", "Complete", "25"),
        ("Performance testing", "Week 4", "Complete", "5"),
        ("Security testing", "Week 4-5", "Complete", "6"),
        ("Regression testing", "Week 5", "Complete", "all (123)"),
    ],

    "test_summary": [
        ("Project", "DAD Asset Management System"),
        ("Total test cases", "123"),
        ("Passed", "119"),
        ("Failed", "4"),
        ("Blocked", "0"),
        ("Pass rate", "96.7%"),
        ("Test lead", "Ittipol Vongapai"),
    ],

    "frontend_results": [
        ("Dashboard", "E2E", "5", "5", "0", "All widgets render correctly"),
        ("Assets list", "E2E + unit", "8", "8", "0", "CRUD and filtering"),
        ("Land parcels", "E2E + unit", "6", "5", "1", "Deed type validation edge case"),
        ("Buildings", "E2E", "5", "5", "0", "Building unit management"),
        ("Vehicles", "E2E", "4", "4", "0", "Vehicle registration CRUD"),
        ("Jewelry", "E2E", "4", "4", "0", "Jewelry appraisal tracking"),
        ("Tenants", "unit", "5", "5", "0", "Tenant registration form"),
        ("Leases", "E2E + unit", "6", "6", "0", "Lease agreement workflow"),
        ("Rent collection", "E2E", "4", "4", "0", "Payment recording"),
        ("Tax", "unit", "5", "5", "0", "Tax calculation validation"),
        ("Documents", "unit", "4", "4", "0", "File upload handling"),
        ("Component library", "unit", "10", "8", "2", "Ant Design wrapper components"),
    ],

    "backend_results": [
        ("Authentication (JWT)", "unit", "5", "5", "0", "Login, register, token refresh"),
        ("Property CRUD", "integration", "5", "5", "0", "Full CRUD cycle"),
        ("Land parcels", "unit + integration", "4", "4", "0", "With Thai deed types"),
        ("Buildings", "integration", "3", "3", "0", "Building plus units"),
        ("Vehicles", "integration", "3", "3", "0", "Vehicle CRUD"),
        ("Jewelry", "integration", "3", "3", "0", "Jewelry with valuations"),
        ("Leases", "unit + integration", "4", "4", "0", "Lease lifecycle"),
        ("Rent collection", "integration", "3", "3", "0", "Payment processing"),
        ("Tax calculation", "unit", "4", "4", "0", "Thai land and vehicle tax"),
        ("FlowAccount sync", "integration", "3", "3", "0", "Contact and invoice sync"),
        ("OCR service", "integration", "2", "2", "0", "Thai text extraction"),
        ("Search", "unit", "2", "2", "0", "Full-text search queries"),
        ("Audit logging", "unit", "2", "2", "0", "Activity log creation"),
        ("Bulk operations", "integration", "2", "2", "0", "Batch import and export"),
        ("Drizzle ORM models", "unit", "5", "4", "1", "Schema validation edge case"),
    ],

    "integration_results": [
        ("Backend to MySQL (Drizzle ORM)", "automated", "PASS", "All model constraints"),
        ("Backend to Redis cache", "automated", "PASS", "Session caching"),
        ("Backend to AWS S3 storage", "manual", "PASS", "Upload, download, and delete"),
        ("Backend to FlowAccount API", "automated", "PASS", "Contact and invoice sync"),
        ("Backend to OCR service", "integration", "PASS", "Thai text extraction"),
        ("Frontend to Backend (REST)", "E2E", "PASS", "All CRUD workflows"),
    ],

    "performance_results": [
        ("GET /api/properties", "100 RPS", "35", "95", "PASS"),
        ("GET /api/land-parcels", "100 RPS", "40", "110", "PASS"),
        ("POST /api/auth/login", "50 RPS", "65", "180", "PASS"),
        ("GET /api/tenants", "80 RPS", "30", "85", "PASS"),
        ("GET /api/dashboard", "100 RPS", "50", "130", "PASS"),
    ],

    "security_results": [
        ("JWT token validation", "Authentication", "PASS", "Expired or malformed tokens rejected"),
        ("RBAC enforcement", "Authorization", "PASS", "Role-based access enforced"),
        ("SQL injection", "Input validation", "PASS", "Parameterized queries via Drizzle ORM"),
        ("XSS prevention", "Input validation", "PASS", "React auto-escaping plus CSP headers"),
        ("CSRF protection", "Session", "PASS", "HTTP-only cookies with SameSite=Lax"),
        ("Input sanitisation", "Validation", "PASS", "Zod schema validation on all endpoints"),
    ],

    "api_coverage": [
        ("/api/auth", "2+", "Yes", "Yes", "Yes", "100%"),
        ("/api/users", "3+", "Yes", "Yes", "No", "90%"),
        ("/api/properties", "5+", "Yes", "Yes", "Yes", "100%"),
        ("/api/land-parcels", "4+", "Yes", "Yes", "No", "95%"),
        ("/api/buildings", "4+", "Yes", "Yes", "No", "90%"),
        ("/api/vehicles", "4+", "Yes", "Yes", "No", "90%"),
        ("/api/jewelry", "4+", "Yes", "Yes", "No", "90%"),
        ("/api/tenants", "3+", "Yes", "Yes", "No", "100%"),
        ("/api/leases", "4+", "Yes", "Yes", "No", "100%"),
        ("/api/billing", "4+", "Yes", "No", "Yes", "85%"),
        ("/api/land-tax", "3+", "Yes", "Yes", "No", "100%"),
        ("/api/vehicle-tax", "3+", "Yes", "Yes", "No", "100%"),
        ("/api/documents", "3+", "Yes", "No", "Yes", "90%"),
        ("/api/flowaccount", "5+", "Yes", "Yes", "No", "95%"),
        ("/api/search", "1+", "Yes", "No", "No", "80%"),
        ("/api/dashboard", "1+", "Yes", "No", "No", "100%"),
    ],

    "defect_summary": [
        ("Critical (P1)", "0", "0", "0", "0"),
        ("Major (P2)", "1", "0", "1", "0"),
        ("Minor (P3)", "3", "0", "2", "1"),
        ("TOTAL", "4", "0", "3", "1"),
    ],

    "defect_details": [
        ("DEF-001", "P2 - Major", "Land parcels",
         "Deed type validation fails for rare Thai deed classifications",
         "Fixed", "Extended the deed type enum"),
        ("DEF-002", "P3 - Minor", "Component library",
         "Ant Design table pagination does not reset on filter change",
         "Fixed", "Added page reset on filter change"),
        ("DEF-003", "P3 - Minor", "Component library",
         "File upload progress indicator stalls on large files",
         "Fixed", "Switched to chunked upload"),
        ("DEF-004", "P3 - Minor", "Drizzle ORM",
         "Schema validation edge case with nullable timestamp fields",
         "Deferred", "Low impact, next sprint"),
    ],

    "code_coverage": [
        ("Frontend (Next.js)", "82%", "76%", "85%", "82%"),
        ("Backend API (Elysia)", "78%", "72%", "80%", "78%"),
        ("OCR service (Python)", "~60%", "~55%", "~65%", "~60%"),
    ],

    "functional_coverage": [
        ("Property management", "10", "10", "100%"),
        ("Lease management", "8", "8", "100%"),
        ("Tenant management", "6", "6", "100%"),
        ("Tax compliance", "8", "8", "100%"),
        ("Utility billing", "6", "6", "100%"),
        ("Document management", "5", "5", "100%"),
        ("User and auth", "6", "6", "100%"),
        ("Search", "3", "3", "100%"),
        ("Reports", "4", "4", "100%"),
        ("FlowAccount sync", "4", "4", "100%"),
    ],

    "entry_criteria": [
        ("Test environment provisioned (AWS EC2, RDS)", "Met", "Services running in ap-southeast-1"),
        ("Application deployed", "Met", "Accessible on the staging URL"),
        ("Test data prepared", "Met", "Organizations, properties, tenants, and leases loaded"),
        ("Test accounts configured", "Met", "Admin, manager, accountant, and viewer roles"),
        ("External services verified", "Met", "FlowAccount sandbox and AWS S3"),
    ],

    "exit_criteria": [
        ("All P1 defects resolved", "0 P1", "0 P1", "PASS"),
        ("All P2 defects resolved", "0 open P2", "0 open (1 fixed)", "PASS"),
        ("Pass rate >= 90%", ">= 90%", "96.7%", "PASS"),
        ("All critical paths tested", "100%", "100%", "PASS"),
        ("API p95 < 500 ms", "< 500 ms", "< 200 ms", "PASS"),
    ],

    "risks": [
        ("Drizzle schema nullable edge case", "Low", "Low", "Deferred to next sprint"),
    ],

    "detailed_test_cases": [
        ("FE-U-001", "Login form validates email format", "Authentication", "PASS"),
        ("FE-U-002", "Asset list renders with Ant Design table", "Assets", "PASS"),
        ("FE-U-003", "Land parcel form handles Thai deed types", "Land parcels", "PASS"),
        ("FE-U-004", "Building form validates unit count", "Buildings", "PASS"),
        ("FE-U-005", "Lease date picker enforces end after start", "Leases", "PASS"),
        ("FE-U-006", "Tax calculator produces correct amounts", "Tax", "PASS"),
        ("FE-U-007", "Document upload handles PDF and images", "Documents", "PASS"),
        ("FE-U-008", "Search returns filtered results", "Search", "PASS"),
        ("FE-E2E-001", "Complete property creation workflow", "Assets", "PASS"),
        ("FE-E2E-002", "Lease creation from property to tenant", "Leases", "PASS"),
        ("FE-E2E-003", "Rent collection full payment cycle", "Rent collection", "PASS"),
        ("FE-E2E-004", "Tax report generation and export", "Tax", "PASS"),
        ("BE-U-001", "JWT token generation and validation", "Authentication", "PASS"),
        ("BE-U-002", "Property CRUD through Drizzle ORM", "Assets", "PASS"),
        ("BE-U-003", "Thai land tax calculation accuracy", "Tax", "PASS"),
        ("BE-U-004", "FlowAccount invoice field mapping", "Integration", "PASS"),
        ("BE-U-005", "OCR Thai text extraction pipeline", "OCR", "PASS"),
        ("BE-U-006", "Audit log creation on CRUD", "Audit", "PASS"),
        ("BE-INT-001", "Property CRUD against real MySQL", "Assets", "PASS"),
        ("BE-INT-002", "Lease lifecycle with tenant", "Leases", "PASS"),
        ("BE-INT-003", "FlowAccount contact sync", "Integration", "PASS"),
    ],

    "db_schema": [
        ("organizations", "id, name, tax_id, address", "Has many users", "Company records"),
        ("users", "id, email, org_id, status", "Belongs to organization", "User accounts"),
        ("roles", "id, name", "Has permissions", "Role definitions"),
        ("properties", "id, type, org_id, status", "Has leases and documents", "All asset types"),
        ("tenants", "id, org_id, name, status", "Has leases", "Tenant records"),
        ("leases", "id, property_id, tenant_id, status", "Belongs to property and tenant", "Lease agreements"),
        ("tax_calculations", "id, property_id, type, amount", "Belongs to property", "Tax amounts"),
        ("documents", "id, entity_type, entity_id, file_url", "Polymorphic", "Uploaded files"),
    ],

    "api_endpoints": [
        ("/api/auth/login", "POST", "User login", "None"),
        ("/api/auth/register", "POST", "User registration", "None"),
        ("/api/users", "GET / POST", "User management", "JWT"),
        ("/api/properties", "GET / POST", "Property listing and creation", "JWT"),
        ("/api/properties/:id", "GET / PUT / DELETE", "Property detail, update, and delete", "JWT"),
        ("/api/land-parcels", "GET / POST", "Land parcel CRUD", "JWT"),
        ("/api/buildings", "GET / POST", "Building CRUD", "JWT"),
        ("/api/vehicles", "GET / POST", "Vehicle CRUD", "JWT"),
        ("/api/jewelry", "GET / POST", "Jewelry CRUD", "JWT"),
        ("/api/tenants", "GET / POST", "Tenant management", "JWT"),
        ("/api/leases", "GET / POST", "Lease management", "JWT"),
        ("/api/rent-collection", "GET / POST", "Rent collection", "JWT"),
        ("/api/payments", "GET / POST", "Payment processing", "JWT"),
        ("/api/billing", "GET / POST", "Billing management", "JWT"),
        ("/api/utilities", "GET / POST", "Utility management", "JWT"),
        ("/api/land-tax", "GET / POST", "Land tax calculations", "JWT"),
        ("/api/vehicle-tax", "GET / POST", "Vehicle tax records", "JWT"),
        ("/api/tax-reports", "GET", "Tax report generation", "JWT"),
        ("/api/documents", "GET / POST", "Document management", "JWT"),
        ("/api/ocr", "POST", "OCR text extraction", "JWT"),
        ("/api/projects", "GET / POST", "Project management", "JWT"),
        ("/api/search", "GET", "Full-text search", "JWT"),
        ("/api/tags", "GET / POST", "Tag management", "JWT"),
        ("/api/flowaccount", "ALL", "FlowAccount sync proxy", "JWT"),
        ("/api/reports", "GET", "Report generation", "JWT"),
        ("/api/dashboard", "GET", "Dashboard statistics", "JWT"),
        ("/api/audit-logs", "GET", "Audit trail", "JWT"),
        ("/api/bulk-operations", "POST", "Batch processing", "JWT"),
    ],
}


# -------------------- Thai overrides --------------------
_TH_OVERRIDES = {
    "description": (
        "แพลตฟอร์มบริหารอสังหาริมทรัพย์และทรัพย์สินของไทย ครอบคลุมที่ดิน อาคาร ยานพาหนะ และอัญมณี "
        "พร้อมระบบจัดการผู้เช่า การเก็บค่าเช่า บิลสาธารณูปโภค การปฏิบัติตามภาษีไทย "
        "การดึงข้อความจากเอกสารด้วย OCR และการเชื่อมต่อระบบบัญชี FlowAccount"
    ),

    "frontend_intro": (
        "ทุกหน้าถูกเรนเดอร์จาก Next.js 14 App Router เพียงชุดเดียว โดยเส้นทางอยู่ภายใต้ "
        "frontend/app/[locale]/... ซึ่งส่วน [locale] จะถูก next-intl แปลงเป็น /en หรือ /th "
        "ก่อนที่โค้ดของหน้าจะทำงาน กลุ่มเส้นทาง (dashboard) รวมหน้าจอปฏิบัติงานที่ต้องล็อกอิน "
        "ส่วน /admin/* ใช้เฉพาะผู้ดูแลระบบ และ /auth/* ใช้สำหรับขั้นตอนล็อกอินสาธารณะ"
    ),

    "auth_description": (
        "ระบบยืนยันตัวตนใช้อีเมลและรหัสผ่าน โดยรหัสผ่านถูกเข้ารหัสด้วย bcrypt เมื่อล็อกอินสำเร็จ "
        "backend จะออก JWT ที่บรรจุรหัสผู้ใช้ รหัสองค์กร และบทบาท token ถูกเก็บใน "
        "คุกกี้แบบ HTTP-only และ SameSite=Lax เพื่อป้องกัน CSRF ทุกคำร้องขอ API จะผ่าน "
        "middleware ของ Elysia ที่ตรวจสอบ JWT และปฏิเสธ token ที่หมดอายุหรือถูกแก้ไข "
        "การอนุญาตสิทธิ์เป็นแบบตามบทบาท (admin, manager, accountant, viewer) โดยบังคับที่ handler "
        "แต่ละตัว และทุกคำค้นถูกจำกัดขอบเขตตามองค์กร ผู้ใช้ขององค์กร A ไม่สามารถเห็นข้อมูลขององค์กร B"
    ),

    "api_services": [
        ("API-001", "Authentication", "/api/auth", "ล็อกอิน สมัครสมาชิก และออก JWT ใหม่"),
        ("API-002", "Users", "/api/users", "จัดการบัญชีผู้ใช้และบทบาท"),
        ("API-003", "Audit Logs", "/api/audit-logs", "บันทึกกิจกรรมของผู้ใช้"),
        ("API-004", "Properties", "/api/properties", "CRUD สำหรับทรัพย์สินทุกประเภท"),
        ("API-005", "Land Parcels", "/api/land-parcels", "CRUD แปลงที่ดิน"),
        ("API-006", "Buildings", "/api/buildings", "CRUD อาคารพร้อมยูนิต"),
        ("API-007", "Vehicles", "/api/vehicles", "CRUD ยานพาหนะ"),
        ("API-008", "Jewelry", "/api/jewelry", "CRUD อัญมณี"),
        ("API-009", "Tenants", "/api/tenants", "ข้อมูลหลักของผู้เช่า"),
        ("API-010", "Leases", "/api/leases", "สัญญาเช่า"),
        ("API-011", "Rent Collection", "/api/rent-collection", "ขั้นตอนเก็บค่าเช่ารายเดือน"),
        ("API-012", "Payments", "/api/payments", "สมุดรายรับรายจ่าย"),
        ("API-013", "Billing", "/api/billing", "บิลระดับอสังหาริมทรัพย์"),
        ("API-014", "Utilities", "/api/utilities", "CRUD บัญชีสาธารณูปโภค"),
        ("API-015", "Utility Packages", "/api/utility-packages", "ตั้งค่าแพ็คเกจบิล"),
        ("API-016", "Tax Reports", "/api/tax-reports", "สร้างรายงานภาษี"),
        ("API-017", "Land Tax", "/api/land-tax", "คำนวณภาษีที่ดินไทย"),
        ("API-018", "Vehicle Tax", "/api/vehicle-tax", "ภาษียานพาหนะไทย"),
        ("API-019", "Documents", "/api/documents", "อัปโหลดและจัดการเอกสาร"),
        ("API-020", "Document Groups", "/api/document-groups", "จัดกลุ่มโฟลเดอร์"),
        ("API-021", "OCR", "/api/ocr", "ดึงข้อความภาษาไทยด้วย OCR"),
        ("API-022", "Projects", "/api/projects", "พื้นที่โครงการ"),
        ("API-023", "Search", "/api/search", "ค้นหาข้อความแบบเต็มข้อความ"),
        ("API-024", "FlowAccount", "/api/flowaccount", "ตัวกลางเชื่อมต่อระบบบัญชี"),
        ("API-025", "Tags", "/api/tags", "ระบบป้ายกำกับ"),
        ("API-026", "Entity Links", "/api/entity-links", "ความสัมพันธ์ข้ามประเภทข้อมูล"),
        ("API-027", "Reports", "/api/reports", "สร้างรายงาน"),
        ("API-028", "Dashboard", "/api/dashboard", "สถิติสำหรับแดชบอร์ด"),
        ("API-029", "Bulk Operations", "/api/bulk-operations", "ประมวลผลเป็นชุด"),
        ("API-030", "Location", "/api/location", "ข้อมูลจังหวัดและอำเภอของไทย"),
    ],

    "db_tables": [
        ("organizations", "ข้อมูลบริษัทหรือองค์กร", "id, name, tax_id"),
        ("users", "บัญชีผู้ใช้ที่ผูกกับองค์กร", "id, email, organization_id"),
        ("roles", "การกำหนดบทบาท", "id, name"),
        ("permissions", "สิทธิ์การใช้งาน", "id, name, action"),
        ("audit_logs", "บันทึกกิจกรรมผู้ใช้", "id, user_id, action, entity"),
        ("asset_types", "ประเภททรัพย์สิน (ที่ดิน / อาคาร / ยานพาหนะ / อัญมณี)", "id, name"),
        ("property_types", "หมวดย่อยของอสังหาริมทรัพย์", "id, name"),
        ("land_deed_types", "ประเภทโฉนดที่ดินไทย", "id, name"),
        ("building_types", "ประเภทอาคาร", "id, name"),
        ("vehicle_types", "ประเภทยานพาหนะ", "id, name"),
        ("jewelry_types", "ประเภทอัญมณี", "id, name"),
        ("tenants", "ข้อมูลผู้เช่า", "id, name, organization_id"),
        ("leases", "สัญญาเช่า", "id, property_id, tenant_id"),
        ("payment_methods", "ประเภทการชำระเงิน", "id, name"),
        ("tax_types", "หมวดภาษี", "id, name"),
        ("tax_calculations", "ยอดภาษีที่คำนวณแล้ว", "id, property_id, tax_type"),
        ("land_tax_assessments", "การประเมินภาษีที่ดินไทย", "id, property_id"),
        ("vehicle_tax_records", "บันทึกภาษียานพาหนะ", "id, vehicle_id"),
        ("utility_accounts", "บัญชีบริการสาธารณูปโภค", "id, property_id"),
        ("utility_bills", "บันทึกบิลสาธารณูปโภค", "id, account_id"),
        ("documents", "เอกสารที่อัปโหลด", "id, entity_type, entity_id"),
        ("document_groups", "โฟลเดอร์เอกสาร", "id, name"),
        ("ocr_results", "ผลการดึงข้อความ OCR", "id, document_id"),
        ("tags", "ป้ายกำกับ", "id, name, color"),
        ("entity_links", "ความเชื่อมโยงข้ามข้อมูล", "id, source_id, target_id"),
        ("projects", "พื้นที่โครงการ", "id, name, organization_id"),
        ("reports", "รายงานที่สร้างแล้ว", "id, type, organization_id"),
        ("provinces", "จังหวัดของไทย", "id, name_th, name_en"),
        ("districts", "อำเภอของไทย", "id, province_id, name"),
        ("flowaccount_contacts", "การซิงก์ผู้ติดต่อ FlowAccount", "id, fa_id, local_id"),
    ],

    "infrastructure": [
        ("Frontend", "Next.js 14", "เว็บ UI แบบ SSR และ static", "Docker"),
        ("Backend API", "Elysia.js on Bun", "เซิร์ฟเวอร์ REST API", "Docker"),
        ("Database", "MySQL 8 (AWS RDS)", "ฐานข้อมูลหลัก", "AWS"),
        ("Cache", "Redis 7", "แคช session และคิวงาน", "Docker"),
        ("Object Storage", "AWS S3 / MinIO", "จัดเก็บเอกสารและรูปภาพ", "AWS / Docker"),
        ("OCR Service", "Python + Tesseract", "ดึงข้อความภาษาไทยจากเอกสาร", "Docker"),
        ("Reverse Proxy", "Nginx", "ตัด SSL และจัดเส้นทาง", "Docker"),
        ("CI / CD", "GitHub Actions", "สายงานสร้าง ทดสอบ และ deploy", "GitHub"),
        ("Container Registry", "GHCR", "เก็บอิมเมจ Docker", "GitHub"),
    ],

    "external_services": [
        ("FlowAccount", "FlowAccount API", "ซิงก์ระบบบัญชีและใบแจ้งหนี้ของไทย", "REST + OAuth"),
        ("AWS S3", "Amazon Web Services", "จัดเก็บเอกสารและรูปภาพ", "SDK"),
        ("AWS RDS", "Amazon Web Services", "ฐานข้อมูล MySQL แบบ managed", "SDK"),
        ("AWS SES", "Amazon Web Services", "อีเมล transactional", "SDK"),
        ("AWS EC2", "Amazon Web Services", "โฮสต์แอปพลิเคชัน", "SSH / Docker"),
    ],

    "security": [
        ("การเก็บรหัสผ่าน", "bcrypt", "เข้ารหัสรหัสผ่านด้วย bcrypt ก่อนบันทึก"),
        ("Session Token", "JWT", "คุกกี้ HTTP-only พร้อมอายุการใช้งานสั้น"),
        ("การอนุญาตสิทธิ์", "RBAC", "บังคับสิทธิ์ตามบทบาทที่ชั้น handler"),
        ("การแยกข้อมูล", "ขอบเขตองค์กร", "ทุกคำค้นถูกกรองด้วย organization_id"),
        ("การส่งข้อมูล", "TLS 1.2+", "บังคับใช้ที่ Nginx"),
        ("CSRF", "SameSite=Lax", "คุกกี้ถูกตั้งค่าให้บล็อกการส่งจากข้ามเว็บ"),
        ("ตรวจสอบข้อมูลเข้า", "Zod", "ตรวจด้วย schema ที่ทุก handler ของ API"),
        ("SQL Injection", "Drizzle ORM", "ใช้ parameterized query เท่านั้น"),
    ],

    "deployment": [
        ("Frontend", "dad-frontend", "3000"),
        ("Backend API", "dad-backend", "3002"),
        ("Database", "AWS RDS MySQL", "3306"),
        ("Redis", "dad-redis", "6379"),
        ("MinIO (dev)", "dad-minio", "9000"),
        ("OCR Service", "dad-ocr", "8000"),
        ("Nginx", "dad-nginx", "80 / 443"),
    ],

    "roles": [
        ("Admin", "CRUD ทั้งหมด จัดการผู้ใช้ และตั้งค่าระบบ", "ทุกโมดูล"),
        ("Manager", "CRUD อสังหาริมทรัพย์ สัญญาเช่า และบิล", "เฉพาะทรัพย์สินที่ได้รับมอบหมาย"),
        ("Accountant", "อ่านและเขียนข้อมูลบิล ภาษี และรายงาน", "โมดูลบิลและภาษี"),
        ("Viewer", "อ่านอย่างเดียว", "เฉพาะโมดูลที่ได้รับมอบหมาย"),
    ],

    "navigation": [
        ("แดชบอร์ด", "/dashboard", "ภาพรวม KPI และกราฟสำคัญ"),
        ("ทรัพย์สิน", "/assets", "คลังทรัพย์สินรวมทุกประเภท"),
        ("แปลงที่ดิน", "/land-parcels", "จัดการแปลงที่ดิน"),
        ("อาคาร", "/buildings", "จัดการอาคาร"),
        ("ผู้เช่า", "/tenants", "ข้อมูลผู้เช่าหลัก"),
        ("สัญญาเช่า", "/leases", "สัญญาเช่าและสถานะ"),
        ("เก็บค่าเช่า", "/rent-collection", "ขั้นตอนเก็บค่าเช่า"),
        ("ภาษี", "/tax", "งานปฏิบัติตามภาษี"),
        ("บิลอสังหาริมทรัพย์", "/property-billing", "บิลระดับอสังหาริมทรัพย์"),
        ("บิลสาธารณูปโภค", "/utility-billing", "บิลค่าน้ำค่าไฟ"),
        ("เอกสาร", "/documents", "จัดการเอกสาร"),
        ("โครงการ", "/projects", "พื้นที่โครงการ"),
        ("ผู้ดูแล — ผู้ใช้", "/admin/users", "จัดการผู้ใช้และบทบาท"),
        ("ผู้ดูแล — Audit Log", "/admin/audit-logs", "บันทึกกิจกรรมของระบบ"),
        ("ผู้ดูแล — ผล OCR", "/admin/ocr-results", "ตรวจทานผลการดึงข้อความ OCR"),
    ],

    "module_design": [
        {"name": "ระบบยืนยันตัวตน",
         "description": "ล็อกอินด้วย JWT บนอีเมลและรหัสผ่าน การอนุญาตสิทธิ์แบบ RBAC บังคับที่ middleware ของ Elysia "
                        "คุกกี้ session เป็นแบบ HTTP-only และ SameSite=Lax",
         "diagram": "dad-access-control.png"},
        {"name": "จัดการทรัพย์สิน",
         "description": "CRUD หลักของทรัพย์สินสี่ประเภท (ที่ดิน อาคาร ยานพาหนะ อัญมณี) แต่ละประเภทมีข้อมูล "
                        "เฉพาะของไทย เช่น ประเภทโฉนด ประเภทยานพาหนะ และประเภทโลหะ",
         "diagram": "dad-module-assets.png"},
        {"name": "ผู้เช่าและสัญญาเช่า",
         "description": "ข้อมูลผู้เช่าหลักและการจัดการวงจรสัญญาเช่า สัญญาเช่าเชื่อมระหว่างอสังหาริมทรัพย์ "
                        "และผู้เช่า พร้อมระยะเวลา ค่าเช่า และตารางการชำระเงิน",
         "diagram": "dad-module-leases.png"},
        {"name": "การเก็บค่าเช่า",
         "description": "รอบเก็บค่าเช่ารายเดือนต่อสัญญา บันทึกการชำระเงิน ติดตามยอดค้างชำระ "
                        "และเชื่อมต่อกับระบบบิลอสังหาริมทรัพย์",
         "diagram": "dad-module-rent-collection.png"},
        {"name": "ภาษีตามกฎหมายไทย",
         "description": "ตัวคำนวณภาษีไทยสำหรับที่ดิน อาคาร ยานพาหนะ และป้าย พร้อมการประเมิน "
                        "สถานะการยื่นแบบ และรายงานภาษีที่ส่งออกได้",
         "diagram": "dad-module-tax.png"},
        {"name": "บิลสาธารณูปโภค",
         "description": "บัญชีสาธารณูปโภคพร้อมการบันทึกมิเตอร์ แพ็คเกจอัตรา และการออกบิลรายเดือน",
         "diagram": "dad-module-utility-billing.png"},
        {"name": "เอกสารและ OCR",
         "description": "อัปโหลดเอกสารขึ้น AWS S3 ดึงข้อความภาษาไทยผ่านบริการ Python + Tesseract "
                        "และเชื่อมโยงแบบ polymorphic กับข้อมูลใดก็ได้ในระบบ",
         "diagram": "dad-module-documents.png"},
        {"name": "ซิงก์ FlowAccount",
         "description": "ส่งข้อมูลผู้ติดต่อ ใบแจ้งหนี้ และใบเสร็จออกไปยัง FlowAccount API "
                        "พร้อมคิวลองใหม่ที่เก็บไว้ใน Redis",
         "diagram": "dad-integration-flowaccount.png"},
    ],

    "test_scope": [
        "Frontend (Next.js 14) — แดชบอร์ด ทรัพย์สิน สัญญาเช่า ภาษี และเอกสาร",
        "Backend API (Elysia.js / Bun) — ทุกกลุ่ม handler ประมาณ 30 กลุ่ม",
        "ฐานข้อมูล MySQL — ความถูกต้องของ schema และ foreign key",
        "การเชื่อมต่อภายนอก — FlowAccount, AWS S3 และบริการ OCR",
        "ความปลอดภัย — การยืนยันตัวตนด้วย JWT, RBAC และการตรวจข้อมูลเข้า",
    ],

    "test_tools": [
        ("Vitest", "latest", "ทดสอบหน่วยฝั่ง frontend", "Frontend"),
        ("React Testing Library", "latest", "ทดสอบ component ของ React", "Frontend"),
        ("Playwright", "latest", "ทดสอบแบบ end-to-end ในเบราว์เซอร์", "Frontend"),
        ("Bun test", "built-in", "ทดสอบหน่วยฝั่ง backend", "Backend"),
        ("Artillery", "2.x", "ทดสอบโหลดและประสิทธิภาพ", "API"),
    ],

    "test_infrastructure": [
        ("เซิร์ฟเวอร์แอป", "AWS EC2 (ap-southeast-1)", "AWS", "ap-southeast-1"),
        ("ฐานข้อมูล", "AWS RDS MySQL 8.x", "AWS", "ap-southeast-1"),
        ("แคช", "Redis 7", "Docker", "เครื่องท้องถิ่น"),
        ("พื้นที่จัดเก็บ", "AWS S3 / MinIO", "AWS / Docker", "-"),
        ("ตัวรัน E2E", "Playwright (Chromium)", "เครื่องท้องถิ่น / CI", "-"),
        ("ทดสอบโหลด", "Artillery", "เครื่องท้องถิ่น", "-"),
    ],

    "test_data": [
        ("องค์กรทดสอบ", "3", "องค์กรผู้ดูแล ผู้จัดการ และบัญชี"),
        ("ผู้ใช้ทดสอบ", "12", "สี่บทบาท คูณสามผู้ใช้"),
        ("อสังหาริมทรัพย์ทดสอบ", "20", "ที่ดิน 8 อาคาร 6 ยานพาหนะ 4 อัญมณี 2"),
        ("ผู้เช่าทดสอบ", "10", "มีสถานะหลากหลาย"),
        ("สัญญาเช่าทดสอบ", "8", "ใช้งาน หมดอายุ และรออนุมัติ"),
        ("รายการภาษีทดสอบ", "15", "การคำนวณภาษีที่ดินและยานพาหนะ"),
        ("เอกสารทดสอบ", "10", "PDF รูปภาพ และตัวอย่าง OCR ภาษาไทย"),
    ],

    "test_strategy": [
        ("ทดสอบหน่วย", "แยกส่วนด้วย mock (Vitest + Bun test)", "อัตโนมัติ 100%", ">= 80%"),
        ("ทดสอบรวมระบบ", "API กับฐานข้อมูลจริง", "อัตโนมัติ 95%", ">= 85%"),
        ("ทดสอบ E2E", "ขั้นตอนใช้งานในเบราว์เซอร์ (Playwright)", "อัตโนมัติ 100%", "เส้นทางหลักครบ 100%"),
        ("ทดสอบประสิทธิภาพ", "ทดสอบโหลด (Artillery)", "อัตโนมัติ 100%", "< 500 ms ที่ p95"),
        ("ทดสอบความปลอดภัย", "ผสมอัตโนมัติและ manual", "อัตโนมัติ 70%", "ครอบคลุมเส้นทาง auth ทั้งหมด"),
    ],

    "test_categories": [
        ("ทดสอบหน่วย frontend", "Vitest", "42", "40", "2", "0", "95.2%"),
        ("ทดสอบ E2E frontend", "Playwright", "25", "24", "1", "0", "96.0%"),
        ("ทดสอบหน่วย backend", "Bun test", "30", "29", "1", "0", "96.7%"),
        ("ทดสอบรวม backend", "manual + API", "15", "15", "0", "0", "100%"),
        ("ทดสอบประสิทธิภาพ", "Artillery", "5", "5", "0", "0", "100%"),
        ("ทดสอบความปลอดภัย", "manual", "6", "6", "0", "0", "100%"),
        ("รวมทั้งหมด", "-", "123", "119", "4", "0", "96.7%"),
    ],

    "test_timeline": [
        ("ทดสอบหน่วย", "สัปดาห์ที่ 1-2", "เสร็จสิ้น", "72"),
        ("ทดสอบรวมระบบ", "สัปดาห์ที่ 2-3", "เสร็จสิ้น", "20"),
        ("ทดสอบ E2E", "สัปดาห์ที่ 3-4", "เสร็จสิ้น", "25"),
        ("ทดสอบประสิทธิภาพ", "สัปดาห์ที่ 4", "เสร็จสิ้น", "5"),
        ("ทดสอบความปลอดภัย", "สัปดาห์ที่ 4-5", "เสร็จสิ้น", "6"),
        ("ทดสอบ regression", "สัปดาห์ที่ 5", "เสร็จสิ้น", "ทั้งหมด (123)"),
    ],

    "test_summary": [
        ("โครงการ", "DAD Asset Management System"),
        ("จำนวนเคสทดสอบทั้งหมด", "123"),
        ("ผ่าน", "119"),
        ("ไม่ผ่าน", "4"),
        ("ถูกบล็อก", "0"),
        ("อัตราผ่าน", "96.7%"),
        ("หัวหน้าทีมทดสอบ", "อิทธิพล วงษ์อภัย"),
    ],

    "frontend_results": [
        ("แดชบอร์ด", "E2E", "5", "5", "0", "ทุก widget แสดงผลถูกต้อง"),
        ("รายการทรัพย์สิน", "E2E + unit", "8", "8", "0", "CRUD และการกรอง"),
        ("แปลงที่ดิน", "E2E + unit", "6", "5", "1", "ตรวจสอบประเภทโฉนดในกรณีขอบ"),
        ("อาคาร", "E2E", "5", "5", "0", "จัดการยูนิตของอาคาร"),
        ("ยานพาหนะ", "E2E", "4", "4", "0", "CRUD การจดทะเบียนยานพาหนะ"),
        ("อัญมณี", "E2E", "4", "4", "0", "ติดตามการประเมินราคาอัญมณี"),
        ("ผู้เช่า", "unit", "5", "5", "0", "ฟอร์มลงทะเบียนผู้เช่า"),
        ("สัญญาเช่า", "E2E + unit", "6", "6", "0", "ขั้นตอนสัญญาเช่า"),
        ("เก็บค่าเช่า", "E2E", "4", "4", "0", "บันทึกการชำระเงิน"),
        ("ภาษี", "unit", "5", "5", "0", "ตรวจสอบการคำนวณภาษี"),
        ("เอกสาร", "unit", "4", "4", "0", "การอัปโหลดไฟล์"),
        ("ไลบรารี component", "unit", "10", "8", "2", "ตัวครอบของ Ant Design"),
    ],

    "backend_results": [
        ("ระบบ JWT", "unit", "5", "5", "0", "ล็อกอิน สมัครสมาชิก ต่ออายุ token"),
        ("CRUD อสังหาริมทรัพย์", "integration", "5", "5", "0", "วงจร CRUD ครบถ้วน"),
        ("แปลงที่ดิน", "unit + integration", "4", "4", "0", "พร้อมประเภทโฉนดไทย"),
        ("อาคาร", "integration", "3", "3", "0", "อาคารพร้อมยูนิต"),
        ("ยานพาหนะ", "integration", "3", "3", "0", "CRUD ยานพาหนะ"),
        ("อัญมณี", "integration", "3", "3", "0", "อัญมณีพร้อมการประเมินราคา"),
        ("สัญญาเช่า", "unit + integration", "4", "4", "0", "วงจรสัญญาเช่า"),
        ("เก็บค่าเช่า", "integration", "3", "3", "0", "ประมวลผลการชำระเงิน"),
        ("คำนวณภาษี", "unit", "4", "4", "0", "ภาษีที่ดินและยานพาหนะไทย"),
        ("ซิงก์ FlowAccount", "integration", "3", "3", "0", "ซิงก์ผู้ติดต่อและใบแจ้งหนี้"),
        ("บริการ OCR", "integration", "2", "2", "0", "ดึงข้อความภาษาไทย"),
        ("ค้นหา", "unit", "2", "2", "0", "คำค้นแบบ full-text"),
        ("บันทึก audit", "unit", "2", "2", "0", "สร้างบันทึกกิจกรรม"),
        ("ประมวลผลเป็นชุด", "integration", "2", "2", "0", "นำเข้า/ส่งออกเป็นชุด"),
        ("โมเดล Drizzle ORM", "unit", "5", "4", "1", "กรณีขอบของ schema"),
    ],

    "integration_results": [
        ("Backend กับ MySQL (Drizzle ORM)", "อัตโนมัติ", "PASS", "ข้อจำกัดของโมเดลทั้งหมด"),
        ("Backend กับ Redis cache", "อัตโนมัติ", "PASS", "แคช session"),
        ("Backend กับ AWS S3", "manual", "PASS", "อัปโหลด ดาวน์โหลด และลบ"),
        ("Backend กับ FlowAccount API", "อัตโนมัติ", "PASS", "ซิงก์ผู้ติดต่อและใบแจ้งหนี้"),
        ("Backend กับบริการ OCR", "integration", "PASS", "ดึงข้อความภาษาไทย"),
        ("Frontend กับ Backend (REST)", "E2E", "PASS", "ทุกขั้นตอน CRUD"),
    ],

    "security_results": [
        ("ตรวจสอบ JWT", "Authentication", "PASS", "ปฏิเสธ token ที่หมดอายุหรือผิดรูป"),
        ("บังคับ RBAC", "Authorization", "PASS", "บังคับสิทธิ์ตามบทบาท"),
        ("SQL Injection", "การตรวจข้อมูลเข้า", "PASS", "ใช้ parameterized query ผ่าน Drizzle ORM"),
        ("ป้องกัน XSS", "การตรวจข้อมูลเข้า", "PASS", "React หลบอักขระพิเศษ พร้อม CSP header"),
        ("ป้องกัน CSRF", "Session", "PASS", "คุกกี้ HTTP-only พร้อม SameSite=Lax"),
        ("กรองข้อมูลเข้า", "ตรวจสอบ", "PASS", "ตรวจสอบด้วย schema ของ Zod ทุก endpoint"),
    ],

    "defect_details": [
        ("DEF-001", "P2 - Major", "แปลงที่ดิน",
         "การตรวจสอบประเภทโฉนดล้มเหลวสำหรับประเภทที่พบไม่บ่อย",
         "แก้ไขแล้ว", "ขยาย enum ของประเภทโฉนด"),
        ("DEF-002", "P3 - Minor", "ไลบรารี component",
         "หน้าตาราง Ant Design ไม่รีเซ็ตเลขหน้าเมื่อเปลี่ยนตัวกรอง",
         "แก้ไขแล้ว", "เพิ่มการรีเซ็ตหน้าเมื่อเปลี่ยนตัวกรอง"),
        ("DEF-003", "P3 - Minor", "ไลบรารี component",
         "ตัวชี้วัดความก้าวหน้าในการอัปโหลดค้างเมื่อไฟล์ใหญ่",
         "แก้ไขแล้ว", "เปลี่ยนไปใช้การอัปโหลดแบบ chunked"),
        ("DEF-004", "P3 - Minor", "Drizzle ORM",
         "กรณีขอบของการตรวจ schema กับฟิลด์ timestamp ที่เป็น null ได้",
         "เลื่อน", "ผลกระทบต่ำ ทำในรอบถัดไป"),
    ],

    "functional_coverage": [
        ("จัดการอสังหาริมทรัพย์", "10", "10", "100%"),
        ("จัดการสัญญาเช่า", "8", "8", "100%"),
        ("จัดการผู้เช่า", "6", "6", "100%"),
        ("ปฏิบัติตามภาษี", "8", "8", "100%"),
        ("บิลสาธารณูปโภค", "6", "6", "100%"),
        ("จัดการเอกสาร", "5", "5", "100%"),
        ("ผู้ใช้และ auth", "6", "6", "100%"),
        ("ค้นหา", "3", "3", "100%"),
        ("รายงาน", "4", "4", "100%"),
        ("ซิงก์ FlowAccount", "4", "4", "100%"),
    ],

    "entry_criteria": [
        ("มีสภาพแวดล้อมทดสอบ (AWS EC2, RDS)", "ผ่าน", "บริการทำงานในภูมิภาค ap-southeast-1"),
        ("แอปพลิเคชันถูก deploy", "ผ่าน", "เข้าถึงได้จาก URL staging"),
        ("เตรียมข้อมูลทดสอบ", "ผ่าน", "โหลดองค์กร อสังหาริมทรัพย์ ผู้เช่า และสัญญาเช่าแล้ว"),
        ("ตั้งบัญชีทดสอบ", "ผ่าน", "บทบาท admin, manager, accountant, viewer"),
        ("ตรวจสอบบริการภายนอก", "ผ่าน", "FlowAccount sandbox และ AWS S3"),
    ],

    "exit_criteria": [
        ("ปิด P1 ได้ทั้งหมด", "0 P1", "0 P1", "PASS"),
        ("ปิด P2 ได้ทั้งหมด", "0 open P2", "0 open (1 แก้ไขแล้ว)", "PASS"),
        ("อัตราผ่าน >= 90%", ">= 90%", "96.7%", "PASS"),
        ("ทดสอบเส้นทางหลักครบถ้วน", "100%", "100%", "PASS"),
        ("API p95 < 500 ms", "< 500 ms", "< 200 ms", "PASS"),
    ],

    "risks": [
        ("กรณีขอบของ schema Drizzle", "ต่ำ", "ต่ำ", "เลื่อนไปรอบถัดไป"),
    ],

    "detailed_test_cases": [
        ("FE-U-001", "ฟอร์มล็อกอินตรวจรูปแบบอีเมล", "Authentication", "PASS"),
        ("FE-U-002", "รายการทรัพย์สินแสดงผลด้วย Ant Design", "ทรัพย์สิน", "PASS"),
        ("FE-U-003", "ฟอร์มแปลงที่ดินรองรับประเภทโฉนดไทย", "แปลงที่ดิน", "PASS"),
        ("FE-U-004", "ฟอร์มอาคารตรวจจำนวนยูนิต", "อาคาร", "PASS"),
        ("FE-U-005", "ตัวเลือกวันที่สัญญาเช่าบังคับ end หลัง start", "สัญญาเช่า", "PASS"),
        ("FE-U-006", "ตัวคำนวณภาษีให้ยอดที่ถูกต้อง", "ภาษี", "PASS"),
        ("FE-U-007", "อัปโหลดเอกสารรองรับ PDF และรูปภาพ", "เอกสาร", "PASS"),
        ("FE-U-008", "การค้นหาให้ผลลัพธ์ที่ถูกกรอง", "ค้นหา", "PASS"),
        ("FE-E2E-001", "ขั้นตอนสร้างอสังหาริมทรัพย์ครบถ้วน", "ทรัพย์สิน", "PASS"),
        ("FE-E2E-002", "สร้างสัญญาเช่าจากอสังหาริมทรัพย์สู่ผู้เช่า", "สัญญาเช่า", "PASS"),
        ("FE-E2E-003", "วงจรเก็บค่าเช่าแบบครบถ้วน", "เก็บค่าเช่า", "PASS"),
        ("FE-E2E-004", "สร้างและส่งออกรายงานภาษี", "ภาษี", "PASS"),
        ("BE-U-001", "สร้างและตรวจสอบ JWT", "Authentication", "PASS"),
        ("BE-U-002", "CRUD อสังหาริมทรัพย์ผ่าน Drizzle ORM", "ทรัพย์สิน", "PASS"),
        ("BE-U-003", "ความแม่นยำของการคำนวณภาษีที่ดินไทย", "ภาษี", "PASS"),
        ("BE-U-004", "แมปฟิลด์ใบแจ้งหนี้ FlowAccount", "Integration", "PASS"),
        ("BE-U-005", "สายประมวลผลข้อความไทยด้วย OCR", "OCR", "PASS"),
        ("BE-U-006", "สร้างบันทึก audit เมื่อทำ CRUD", "Audit", "PASS"),
        ("BE-INT-001", "CRUD อสังหาริมทรัพย์กับ MySQL จริง", "ทรัพย์สิน", "PASS"),
        ("BE-INT-002", "วงจรสัญญาเช่ากับผู้เช่า", "สัญญาเช่า", "PASS"),
        ("BE-INT-003", "ซิงก์ผู้ติดต่อ FlowAccount", "Integration", "PASS"),
    ],

    "db_schema": [
        ("organizations", "id, name, tax_id, address", "มีผู้ใช้หลายคน", "ข้อมูลองค์กร"),
        ("users", "id, email, org_id, status", "อยู่ในองค์กร", "บัญชีผู้ใช้"),
        ("roles", "id, name", "มีสิทธิ์หลายรายการ", "นิยามบทบาท"),
        ("properties", "id, type, org_id, status", "มีสัญญาเช่าและเอกสาร", "ทุกประเภททรัพย์สิน"),
        ("tenants", "id, org_id, name, status", "มีสัญญาเช่า", "ข้อมูลผู้เช่า"),
        ("leases", "id, property_id, tenant_id, status", "อยู่ภายใต้อสังหาริมทรัพย์และผู้เช่า", "สัญญาเช่า"),
        ("tax_calculations", "id, property_id, type, amount", "อยู่ภายใต้อสังหาริมทรัพย์", "ยอดภาษี"),
        ("documents", "id, entity_type, entity_id, file_url", "Polymorphic", "ไฟล์ที่อัปโหลด"),
    ],

    "api_endpoints": [
        ("/api/auth/login", "POST", "ล็อกอิน", "ไม่ต้อง"),
        ("/api/auth/register", "POST", "สมัครสมาชิก", "ไม่ต้อง"),
        ("/api/users", "GET / POST", "จัดการผู้ใช้", "JWT"),
        ("/api/properties", "GET / POST", "รายการและสร้างอสังหาริมทรัพย์", "JWT"),
        ("/api/properties/:id", "GET / PUT / DELETE", "อ่าน แก้ไข และลบรายละเอียด", "JWT"),
        ("/api/land-parcels", "GET / POST", "CRUD แปลงที่ดิน", "JWT"),
        ("/api/buildings", "GET / POST", "CRUD อาคาร", "JWT"),
        ("/api/vehicles", "GET / POST", "CRUD ยานพาหนะ", "JWT"),
        ("/api/jewelry", "GET / POST", "CRUD อัญมณี", "JWT"),
        ("/api/tenants", "GET / POST", "จัดการผู้เช่า", "JWT"),
        ("/api/leases", "GET / POST", "จัดการสัญญาเช่า", "JWT"),
        ("/api/rent-collection", "GET / POST", "เก็บค่าเช่า", "JWT"),
        ("/api/payments", "GET / POST", "ประมวลผลการชำระเงิน", "JWT"),
        ("/api/billing", "GET / POST", "จัดการบิล", "JWT"),
        ("/api/utilities", "GET / POST", "จัดการสาธารณูปโภค", "JWT"),
        ("/api/land-tax", "GET / POST", "คำนวณภาษีที่ดิน", "JWT"),
        ("/api/vehicle-tax", "GET / POST", "บันทึกภาษียานพาหนะ", "JWT"),
        ("/api/tax-reports", "GET", "สร้างรายงานภาษี", "JWT"),
        ("/api/documents", "GET / POST", "จัดการเอกสาร", "JWT"),
        ("/api/ocr", "POST", "ดึงข้อความด้วย OCR", "JWT"),
        ("/api/projects", "GET / POST", "จัดการโครงการ", "JWT"),
        ("/api/search", "GET", "ค้นหาข้อความ", "JWT"),
        ("/api/tags", "GET / POST", "จัดการป้ายกำกับ", "JWT"),
        ("/api/flowaccount", "ALL", "ตัวกลางซิงก์ FlowAccount", "JWT"),
        ("/api/reports", "GET", "สร้างรายงาน", "JWT"),
        ("/api/dashboard", "GET", "สถิติแดชบอร์ด", "JWT"),
        ("/api/audit-logs", "GET", "บันทึก audit", "JWT"),
        ("/api/bulk-operations", "POST", "ประมวลผลเป็นชุด", "JWT"),
    ],
}


def get_analysis(lang):
    """Return lang-specific analysis. Falls back to EN for unknown langs."""
    out = dict(_EN)
    if lang == "th":
        out.update(_TH_OVERRIDES)
    return out


# Backwards-compat: a plain `analysis` dict (EN) is kept for any caller that
# still imports it directly.
analysis = dict(_EN)
